# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ksengine
open_collective: ksengine
ko_fi: ksengine
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ksengine
issuehunt: ksengine
otechie: # Replace with a single Otechie username
custom: ['buymeacoff.ee/ksengine']
